import { LevelDefinition } from '../../types/horrorGame';

export const BACKROOMS_LEVELS: LevelDefinition[] = [
  {
    id: 0,
    title: 'LEVEL 0',
    subtitle: 'THE YELLOW MONOTONY',
    description: 'An endless non-linear expanse of uniform segmented rooms. Damp vintage wallpaper, buzzing fluorescent ballasts, and sodden rotting carpet.',
    survivalClass: 'Class 1 (Habitable)',
    wallTextureType: 'yellow_wallpaper',
    floorTextureType: 'damp_carpet',
    ceilingTextureType: 'acoustic_tiles',
    ambientColor: '#8a7d52',
    fogColor: '#4a4328',
    fogDensity: 0.045,
    ceilingHeight: 3.2,
    dronePitch: 120, // 60Hz harmonic buzz
    hasWaterPuddles: false,
    entitiesAllowed: ['stalker', 'mimic'],
    anomalyFrequency: 0.35,
    exitCondition: 'find_elevator'
  },
  {
    id: 1,
    title: 'LEVEL 1',
    subtitle: 'HABITABLE INDUSTRIAL ZONE',
    description: 'Vast warehouse corridors with exposed rebar, low-hanging steam pipes, flickering sodium spotlights, and puddles of anomalous condensation.',
    survivalClass: 'Class 1 (Habitable)',
    wallTextureType: 'concrete',
    floorTextureType: 'wet_concrete',
    ceilingTextureType: 'concrete_slab',
    ambientColor: '#475569',
    fogColor: '#1e293b',
    fogDensity: 0.06,
    ceilingHeight: 4.0,
    dronePitch: 85,
    hasWaterPuddles: true,
    entitiesAllowed: ['listener', 'smiler'],
    anomalyFrequency: 0.5,
    exitCondition: 'fuse_puzzle'
  },
  {
    id: 2,
    title: 'LEVEL 2',
    subtitle: 'PIPE DREAMS',
    description: 'Suffocatingly hot maintenance catacombs lined with vibrating high-pressure steam pipes. Visceral acoustic echo and sudden pressure blowouts.',
    survivalClass: 'Class 2 (Insecure)',
    wallTextureType: 'pipe_corridor',
    floorTextureType: 'grated_metal',
    ceilingTextureType: 'pipes_ceiling',
    ambientColor: '#78350f',
    fogColor: '#271005',
    fogDensity: 0.075,
    ceilingHeight: 2.8,
    dronePitch: 160,
    hasWaterPuddles: true,
    entitiesAllowed: ['listener', 'stalker'],
    anomalyFrequency: 0.65,
    exitCondition: 'valve_sequence'
  },
  {
    id: 3,
    title: 'LEVEL 3',
    subtitle: 'ELECTRICAL SUB-STATION',
    description: 'Dangerous maze of high-voltage transformers and dark brick chambers. Arcing electrical sparks intermittently light up pitch-black corners.',
    survivalClass: 'Class 3 (Unsafe)',
    wallTextureType: 'industrial_brick',
    floorTextureType: 'wet_concrete',
    ceilingTextureType: 'concrete_slab',
    ambientColor: '#1e1b4b',
    fogColor: '#090724',
    fogDensity: 0.07,
    ceilingHeight: 3.5,
    dronePitch: 240,
    hasWaterPuddles: false,
    entitiesAllowed: ['smiler', 'mimic'],
    anomalyFrequency: 0.75,
    exitCondition: 'fuse_puzzle'
  },
  {
    id: 4,
    title: 'LEVEL 4',
    subtitle: 'ABANDONED CORPORATE OFFICE',
    description: 'Endless rows of empty beige cubicles and windows facing an impossible black void. Occasional rotary phones ring in distant rooms with no one calling.',
    survivalClass: 'Class 1 (Habitable)',
    wallTextureType: 'office_panel',
    floorTextureType: 'tiled_floor',
    ceilingTextureType: 'acoustic_tiles',
    ambientColor: '#64748b',
    fogColor: '#0f172a',
    fogDensity: 0.04,
    ceilingHeight: 3.0,
    dronePitch: 95,
    hasWaterPuddles: false,
    entitiesAllowed: ['mimic', 'stalker'],
    anomalyFrequency: 0.45,
    exitCondition: 'find_elevator'
  },
  {
    id: 5,
    title: 'LEVEL 5',
    subtitle: 'HOTEL LIMBO',
    description: 'An expansive 1930s grand hotel with blood-red damask walls, ornate creaking floorboards, and elevator doors that open to solid brick walls.',
    survivalClass: 'Class 2 (Insecure)',
    wallTextureType: 'hotel_wallpaper',
    floorTextureType: 'hotel_carpet',
    ceilingTextureType: 'hotel_ceiling',
    ambientColor: '#7f1d1d',
    fogColor: '#2b0707',
    fogDensity: 0.05,
    ceilingHeight: 3.4,
    dronePitch: 105,
    hasWaterPuddles: false,
    entitiesAllowed: ['mimic', 'listener'],
    anomalyFrequency: 0.7,
    exitCondition: 'find_elevator'
  },
  {
    id: 6,
    title: 'LEVEL 6',
    subtitle: 'LIGHTS OUT',
    description: 'A space of anomalous photon absorption. Natural and artificial light decay rapidly. Sound propagation is warped, making navigation purely acoustic.',
    survivalClass: 'Class 4 (Hazardous)',
    wallTextureType: 'pitch_black',
    floorTextureType: 'void',
    ceilingTextureType: 'darkness',
    ambientColor: '#020202',
    fogColor: '#000000',
    fogDensity: 0.12,
    ceilingHeight: 4.5,
    dronePitch: 50,
    hasWaterPuddles: false,
    entitiesAllowed: ['smiler', 'listener'],
    anomalyFrequency: 0.9,
    exitCondition: 'darkness_leap'
  }
];
