import { TileDef, ItemDef, TileId } from '../../types/platformerGame';

export const TILE_DEFINITIONS: Record<TileId, TileDef> = {
  0: {
    id: 0,
    name: 'Air',
    hardness: 0,
    bestTool: 'none',
    minToolTier: 0,
    isSolid: false,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: 'transparent',
    dropItemId: '',
    dropCount: 0
  },
  1: {
    id: 1,
    name: 'Grass Turf',
    hardness: 0.4,
    bestTool: 'pickaxe',
    minToolTier: 0,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#22c55e',
    accentColor: '#15803d',
    dropItemId: 'item_dirt',
    dropCount: 1
  },
  2: {
    id: 2,
    name: 'Aether Loam',
    hardness: 0.35,
    bestTool: 'pickaxe',
    minToolTier: 0,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#78350f',
    accentColor: '#592506',
    dropItemId: 'item_dirt',
    dropCount: 1
  },
  3: {
    id: 3,
    name: 'Granite Stone',
    hardness: 0.8,
    bestTool: 'pickaxe',
    minToolTier: 1,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#64748b',
    accentColor: '#475569',
    dropItemId: 'item_stone',
    dropCount: 1
  },
  4: {
    id: 4,
    name: 'Sunwood Log',
    hardness: 0.5,
    bestTool: 'axe',
    minToolTier: 0,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#a16207',
    accentColor: '#713f12',
    dropItemId: 'item_wood_log',
    dropCount: 1
  },
  5: {
    id: 5,
    name: 'Sunwood Leaves',
    hardness: 0.15,
    bestTool: 'none',
    minToolTier: 0,
    isSolid: false,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#16a34a',
    dropItemId: 'item_sapling',
    dropCount: 1
  },
  6: {
    id: 6,
    name: 'Sunwood Planks',
    hardness: 0.4,
    bestTool: 'axe',
    minToolTier: 0,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#d97706',
    accentColor: '#b45309',
    dropItemId: 'item_wood_plank',
    dropCount: 1
  },
  7: {
    id: 7,
    name: 'Scorched Sand',
    hardness: 0.3,
    bestTool: 'pickaxe',
    minToolTier: 0,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#fde047',
    accentColor: '#eab308',
    dropItemId: 'item_sand',
    dropCount: 1
  },
  8: {
    id: 8,
    name: 'Sandstone',
    hardness: 0.7,
    bestTool: 'pickaxe',
    minToolTier: 1,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#ca8a04',
    dropItemId: 'item_sandstone',
    dropCount: 1
  },
  9: {
    id: 9,
    name: 'Frosted Snow',
    hardness: 0.25,
    bestTool: 'pickaxe',
    minToolTier: 0,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#f8fafc',
    dropItemId: 'item_snowball',
    dropCount: 2
  },
  10: {
    id: 10,
    name: 'Glacial Ice',
    hardness: 0.6,
    bestTool: 'pickaxe',
    minToolTier: 1,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#38bdf8',
    dropItemId: 'item_ice',
    dropCount: 1
  },
  11: {
    id: 11,
    name: 'Ironite Ore',
    hardness: 1.2,
    bestTool: 'pickaxe',
    minToolTier: 1,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#ea580c',
    accentColor: '#475569',
    dropItemId: 'item_raw_ironite',
    dropCount: 1
  },
  12: {
    id: 12,
    name: 'Cobalt Ore',
    hardness: 1.6,
    bestTool: 'pickaxe',
    minToolTier: 2,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 2,
    color: '#06b6d4',
    accentColor: '#334155',
    dropItemId: 'item_raw_cobalt',
    dropCount: 1
  },
  13: {
    id: 13,
    name: 'Prism Crystal Ore',
    hardness: 2.2,
    bestTool: 'pickaxe',
    minToolTier: 3,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 6,
    color: '#ec4899',
    accentColor: '#1e1b4b',
    dropItemId: 'item_prism_crystal',
    dropCount: 2
  },
  14: {
    id: 14,
    name: 'Voidstone Ore',
    hardness: 3.0,
    bestTool: 'pickaxe',
    minToolTier: 4,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#312e81',
    accentColor: '#4338ca',
    dropItemId: 'item_void_shard',
    dropCount: 1
  },
  15: {
    id: 15,
    name: 'Wooden Platform',
    hardness: 0.25,
    bestTool: 'axe',
    minToolTier: 0,
    isSolid: false,
    isPlatform: true, // Jump through from below, stand on top, drop through with Down+Jump!
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#d97706',
    dropItemId: 'item_platform',
    dropCount: 1
  },
  16: {
    id: 16,
    name: 'Wooden Door (Closed)',
    hardness: 0.5,
    bestTool: 'axe',
    minToolTier: 0,
    isSolid: true, // Blocks passage when closed
    isPlatform: false,
    isDoor: true,
    isOpenDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#92400e',
    dropItemId: 'item_door',
    dropCount: 1
  },
  17: {
    id: 17,
    name: 'Wooden Door (Open)',
    hardness: 0.5,
    bestTool: 'axe',
    minToolTier: 0,
    isSolid: false, // Walk through when open
    isPlatform: false,
    isDoor: true,
    isOpenDoor: true,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#b45309',
    dropItemId: 'item_door',
    dropCount: 1
  },
  18: {
    id: 18,
    name: 'Aether Torch',
    hardness: 0.1,
    bestTool: 'none',
    minToolTier: 0,
    isSolid: false,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 14, // Strong light
    color: '#f59e0b',
    dropItemId: 'item_torch',
    dropCount: 1
  },
  19: {
    id: 19,
    name: 'Crafting Workbench',
    hardness: 0.6,
    bestTool: 'axe',
    minToolTier: 0,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: true,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#b45309',
    accentColor: '#fde047',
    dropItemId: 'item_workbench',
    dropCount: 1
  },
  20: {
    id: 20,
    name: 'Smelting Furnace',
    hardness: 1.0,
    bestTool: 'pickaxe',
    minToolTier: 1,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: true,
    isAnvil: false,
    isLadder: false,
    lightEmission: 8,
    color: '#475569',
    accentColor: '#f97316',
    dropItemId: 'item_furnace',
    dropCount: 1
  },
  21: {
    id: 21,
    name: 'Metal Anvil',
    hardness: 1.2,
    bestTool: 'pickaxe',
    minToolTier: 1,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: true,
    isLadder: false,
    lightEmission: 0,
    color: '#334155',
    dropItemId: 'item_anvil',
    dropCount: 1
  },
  22: {
    id: 22,
    name: 'Storage Chest',
    hardness: 0.6,
    bestTool: 'axe',
    minToolTier: 0,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: true,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#78350f',
    accentColor: '#f59e0b',
    dropItemId: 'item_chest',
    dropCount: 1
  },
  23: {
    id: 23,
    name: 'Wood Ladder',
    hardness: 0.2,
    bestTool: 'axe',
    minToolTier: 0,
    isSolid: false,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: true, // Climbable with Up/Down keys
    lightEmission: 0,
    color: '#92400e',
    dropItemId: 'item_ladder',
    dropCount: 1
  },
  24: {
    id: 24,
    name: 'Glass Window',
    hardness: 0.2,
    bestTool: 'none',
    minToolTier: 0,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#e0f2fe',
    dropItemId: 'item_glass',
    dropCount: 1
  },
  25: {
    id: 25,
    name: 'Stone Bricks',
    hardness: 1.0,
    bestTool: 'pickaxe',
    minToolTier: 1,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#94a3b8',
    accentColor: '#334155',
    dropItemId: 'item_brick',
    dropCount: 1
  },
  26: {
    id: 26,
    name: 'Campfire',
    hardness: 0.4,
    bestTool: 'axe',
    minToolTier: 0,
    isSolid: false,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 13,
    color: '#ea580c',
    dropItemId: 'item_campfire',
    dropCount: 1
  },
  27: {
    id: 27,
    name: 'Wild Herbs',
    hardness: 0.1,
    bestTool: 'none',
    minToolTier: 0,
    isSolid: false,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#84cc16',
    dropItemId: 'item_herbs',
    dropCount: 2
  },
  28: {
    id: 28,
    name: 'Obsidian Strata',
    hardness: 3.5,
    bestTool: 'pickaxe',
    minToolTier: 3,
    isSolid: true,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 0,
    color: '#0f172a',
    accentColor: '#581c87',
    dropItemId: 'item_obsidian',
    dropCount: 1
  },
  29: {
    id: 29,
    name: 'Magma Core',
    hardness: 0,
    bestTool: 'none',
    minToolTier: 0,
    isSolid: false,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 15,
    color: '#dc2626',
    dropItemId: '',
    dropCount: 0
  },
  30: {
    id: 30,
    name: 'Radiant Crystal Lamp',
    hardness: 0.3,
    bestTool: 'none',
    minToolTier: 0,
    isSolid: false,
    isPlatform: false,
    isDoor: false,
    isChest: false,
    isWorkbench: false,
    isFurnace: false,
    isAnvil: false,
    isLadder: false,
    lightEmission: 15,
    color: '#fef08a',
    dropItemId: 'item_lamp',
    dropCount: 1
  }
};

export const WALL_DEFINITIONS: Record<number, { id: number; name: string; color: string; dropItemId: string }> = {
  0: { id: 0, name: 'No Wall', color: 'transparent', dropItemId: '' },
  101: { id: 101, name: 'Wood Wall', color: '#592506', dropItemId: 'item_wood_wall' },
  102: { id: 102, name: 'Stone Wall', color: '#334155', dropItemId: 'item_stone_wall' },
  103: { id: 103, name: 'Dirt Wall', color: '#451a03', dropItemId: 'item_dirt_wall' },
  104: { id: 104, name: 'Brick Wall', color: '#64748b', dropItemId: 'item_brick_wall' }
};

export const ITEM_REGISTRY: Record<string, ItemDef> = {
  // Tiles / Blocks
  item_dirt: { id: 'item_dirt', name: 'Aether Loam', description: 'Rich soil for building or farming.', category: 'tile', maxStack: 999, placeTileId: 2 },
  item_stone: { id: 'item_stone', name: 'Granite Stone', description: 'Solid rock quarried from underground.', category: 'tile', maxStack: 999, placeTileId: 3 },
  item_wood_log: { id: 'item_wood_log', name: 'Sunwood Timber', description: 'Sturdy golden wood trunk.', category: 'material', maxStack: 999 },
  item_wood_plank: { id: 'item_wood_plank', name: 'Sunwood Planks', description: 'Refined construction timber.', category: 'tile', maxStack: 999, placeTileId: 6 },
  item_platform: { id: 'item_platform', name: 'Wooden Platform', description: 'One-way platform. Press Down+Jump to drop through.', category: 'tile', maxStack: 999, placeTileId: 15 },
  item_door: { id: 'item_door', name: 'Wooden Door', description: 'Interactive shelter door. Right-click or tap to open/close.', category: 'furniture', maxStack: 99, placeTileId: 16 },
  item_ladder: { id: 'item_ladder', name: 'Wood Ladder', description: 'Climbable ladder for vertical mine shafts.', category: 'tile', maxStack: 999, placeTileId: 23 },
  item_sand: { id: 'item_sand', name: 'Scorched Sand', description: 'Fine silica sand.', category: 'tile', maxStack: 999, placeTileId: 7 },
  item_sandstone: { id: 'item_sandstone', name: 'Sandstone', description: 'Compacted desert stone.', category: 'tile', maxStack: 999, placeTileId: 8 },
  item_snowball: { id: 'item_snowball', name: 'Snowball', description: 'Chilled snow sphere.', category: 'material', maxStack: 999 },
  item_ice: { id: 'item_ice', name: 'Glacial Ice', description: 'Slippery frozen block.', category: 'tile', maxStack: 999, placeTileId: 10 },
  item_brick: { id: 'item_brick', name: 'Stone Brick', description: 'Reinforced masonry building block.', category: 'tile', maxStack: 999, placeTileId: 25 },
  item_glass: { id: 'item_glass', name: 'Glass Window', description: 'Smelted transparent window block.', category: 'tile', maxStack: 999, placeTileId: 24 },
  item_torch: { id: 'item_torch', name: 'Aether Torch', description: 'Provides bright perimeter lighting in dark caves.', category: 'furniture', maxStack: 999, placeTileId: 18 },
  item_lamp: { id: 'item_lamp', name: 'Radiant Lamp', description: 'High-intensity aether crystal light source.', category: 'furniture', maxStack: 99, placeTileId: 30 },
  item_workbench: { id: 'item_workbench', name: 'Crafting Workbench', description: 'Unlocks advanced recipes when placed nearby.', category: 'furniture', maxStack: 99, placeTileId: 19 },
  item_furnace: { id: 'item_furnace', name: 'Smelting Furnace', description: 'Smelts raw ores into refined metal ingots.', category: 'furniture', maxStack: 99, placeTileId: 20 },
  item_anvil: { id: 'item_anvil', name: 'Metal Anvil', description: 'Forges heavy weaponry, broadswords and armor.', category: 'furniture', maxStack: 99, placeTileId: 21 },
  item_chest: { id: 'item_chest', name: 'Storage Chest', description: 'Holds 20 items. Persistent across game sessions.', category: 'furniture', maxStack: 99, placeTileId: 22 },
  item_campfire: { id: 'item_campfire', name: 'Campfire', description: 'Provides warm light and healing aura.', category: 'furniture', maxStack: 99, placeTileId: 26 },
  item_sapling: { id: 'item_sapling', name: 'Tree Sapling', description: 'Sprouts into a sunwood tree over time.', category: 'material', maxStack: 999 },
  item_herbs: { id: 'item_herbs', name: 'Wild Herbs', description: 'Medicinal flora for brewing healing salves.', category: 'material', maxStack: 999 },
  item_obsidian: { id: 'item_obsidian', name: 'Obsidian Slab', description: 'Volcanic glass rock from deep underground.', category: 'tile', maxStack: 999, placeTileId: 28 },

  // Background Walls
  item_wood_wall: { id: 'item_wood_wall', name: 'Wood Wall', description: 'Background wooden wall for enclosed rooms.', category: 'wall', maxStack: 999, placeWallId: 101 },
  item_stone_wall: { id: 'item_stone_wall', name: 'Stone Wall', description: 'Background stone wall for castles and dungeons.', category: 'wall', maxStack: 999, placeWallId: 102 },
  item_dirt_wall: { id: 'item_dirt_wall', name: 'Dirt Wall', description: 'Background earth wall.', category: 'wall', maxStack: 999, placeWallId: 103 },
  item_brick_wall: { id: 'item_brick_wall', name: 'Brick Wall', description: 'Decorative background masonry wall.', category: 'wall', maxStack: 999, placeWallId: 104 },

  // Ores & Ingots
  item_raw_ironite: { id: 'item_raw_ironite', name: 'Raw Ironite Ore', description: 'Unrefined ironite mined from shallow caves.', category: 'material', maxStack: 999 },
  item_ingot_ironite: { id: 'item_ingot_ironite', name: 'Ironite Ingot', description: 'Smelted industrial metal.', category: 'material', maxStack: 999 },
  item_raw_cobalt: { id: 'item_raw_cobalt', name: 'Raw Cobalt Ore', description: 'Blue deep-strata high-tensile ore.', category: 'material', maxStack: 999 },
  item_ingot_cobalt: { id: 'item_ingot_cobalt', name: 'Cobalt Ingot', description: 'Heavy blue alloy for tier 3 equipment.', category: 'material', maxStack: 999 },
  item_prism_crystal: { id: 'item_prism_crystal', name: 'Prism Crystal', description: 'Resonant gem found in deep geodes.', category: 'material', maxStack: 999 },
  item_void_shard: { id: 'item_void_shard', name: 'Void Shard', description: 'Cosmic matter from the deep magma stratum.', category: 'material', maxStack: 999 },
  item_stick: { id: 'item_stick', name: 'Wooden Stick', description: 'Essential component for crafting tools and weapons.', category: 'material', maxStack: 999 },

  // Tools: Pickaxes
  tool_wood_pick: { id: 'tool_wood_pick', name: 'Wooden Pickaxe', description: 'Mines stone and shallow dirt (Speed: 1.2x).', category: 'tool', maxStack: 1, toolType: 'pickaxe', toolTier: 1, miningSpeed: 1.2 },
  tool_stone_pick: { id: 'tool_stone_pick', name: 'Stone Pickaxe', description: 'Mines Ironite and hard stone (Speed: 2.0x).', category: 'tool', maxStack: 1, toolType: 'pickaxe', toolTier: 2, miningSpeed: 2.0 },
  tool_iron_pick: { id: 'tool_iron_pick', name: 'Ironite Pickaxe', description: 'Mines Cobalt and deep strata (Speed: 3.5x).', category: 'tool', maxStack: 1, toolType: 'pickaxe', toolTier: 3, miningSpeed: 3.5 },
  tool_cobalt_pick: { id: 'tool_cobalt_pick', name: 'Cobalt Pickaxe', description: 'Rapidly pierces Voidstone and Prism ores (Speed: 5.5x).', category: 'tool', maxStack: 1, toolType: 'pickaxe', toolTier: 4, miningSpeed: 5.5 },
  tool_prism_drill: { id: 'tool_prism_drill', name: 'Prism Laser-Drill', description: 'Supreme mining tool. Vaporizes all tiles (Speed: 9.0x).', category: 'tool', maxStack: 1, toolType: 'pickaxe', toolTier: 5, miningSpeed: 9.0 },

  // Tools: Axes & Hammers
  tool_wood_axe: { id: 'tool_wood_axe', name: 'Wooden Axe', description: 'Chops sunwood trees efficiently.', category: 'tool', maxStack: 1, toolType: 'axe', toolTier: 1, miningSpeed: 1.5 },
  tool_iron_axe: { id: 'tool_iron_axe', name: 'Ironite Axe', description: 'Heavy woodcutter axe.', category: 'tool', maxStack: 1, toolType: 'axe', toolTier: 3, miningSpeed: 3.5 },
  tool_wood_hammer: { id: 'tool_wood_hammer', name: 'Wooden Hammer', description: 'Breaks and modifies background walls.', category: 'tool', maxStack: 1, toolType: 'hammer', toolTier: 1, miningSpeed: 2.0 },

  // Weapons
  weapon_wood_sword: { id: 'weapon_wood_sword', name: 'Sunwood Blade', description: 'Light timber sword (8 DMG).', category: 'weapon', maxStack: 1, toolType: 'sword', damage: 8 },
  weapon_iron_sword: { id: 'weapon_iron_sword', name: 'Ironite Broadsword', description: 'Forged steel blade (16 DMG).', category: 'weapon', maxStack: 1, toolType: 'sword', damage: 16 },
  weapon_cobalt_sword: { id: 'weapon_cobalt_sword', name: 'Cobalt Greatsword', description: 'Heavy deep-strike weapon (28 DMG, High Knockback).', category: 'weapon', maxStack: 1, toolType: 'sword', damage: 28 },
  weapon_prism_saber: { id: 'weapon_prism_saber', name: 'Prism Light-Saber', description: 'Energy blade slicing through monsters (45 DMG).', category: 'weapon', maxStack: 1, toolType: 'sword', damage: 45 },
  weapon_bow: { id: 'weapon_bow', name: 'Recurve Bow', description: 'Fires wooden arrows at range (14 DMG).', category: 'weapon', maxStack: 1, toolType: 'bow', damage: 14 },
  item_arrow: { id: 'item_arrow', name: 'Wooden Arrow', description: 'Ammunition for bows.', category: 'material', maxStack: 999 },

  // Armor
  armor_iron_helm: { id: 'armor_iron_helm', name: 'Ironite Helmet', description: '+4 Defense.', category: 'armor', maxStack: 1, armorValue: 4 },
  armor_iron_chest: { id: 'armor_iron_chest', name: 'Ironite Chestplate', description: '+8 Defense.', category: 'armor', maxStack: 1, armorValue: 8 },
  armor_iron_boots: { id: 'armor_iron_boots', name: 'Ironite Greaves', description: '+4 Defense.', category: 'armor', maxStack: 1, armorValue: 4 },
  armor_cobalt_helm: { id: 'armor_cobalt_helm', name: 'Cobalt Helmet', description: '+8 Defense.', category: 'armor', maxStack: 1, armorValue: 8 },
  armor_cobalt_chest: { id: 'armor_cobalt_chest', name: 'Cobalt Chestplate', description: '+16 Defense.', category: 'armor', maxStack: 1, armorValue: 16 },
  armor_cobalt_boots: { id: 'armor_cobalt_boots', name: 'Cobalt Greaves', description: '+8 Defense.', category: 'armor', maxStack: 1, armorValue: 8 },

  // Consumables
  item_salve: { id: 'item_salve', name: 'Herb Healing Salve', description: 'Restores 35 Health instantly.', category: 'consumable', maxStack: 30, healAmount: 35 },
  item_bread: { id: 'item_bread', name: 'Baked Bread', description: 'Restores 20 Health and 40 Stamina.', category: 'consumable', maxStack: 30, healAmount: 20, staminaAmount: 40 }
};
