import { PlantCardDef, ZombieCardDef, CommanderSpellDef, MapType, TileHazard } from '../../types/pvpClash';

export const PLANT_REGISTRY: Record<string, PlantCardDef> = {
  plant_sunsprout: {
    id: 'plant_sunsprout',
    name: 'Solar Sprout',
    description: 'Generates 25 Solar Energy every 8 seconds.',
    cost: 50,
    cooldown: 5.0,
    health: 300,
    attackDamage: 0,
    attackInterval: 8.0,
    range: 0,
    projectileType: 'none',
    plantRole: 'sun',
    color: '#facc15',
    accentColor: '#eab308'
  },
  plant_peablaster: {
    id: 'plant_peablaster',
    name: 'Pea Blaster',
    description: 'Shoots straightforward plasma peas down the lane.',
    cost: 100,
    cooldown: 6.0,
    health: 300,
    attackDamage: 22,
    attackInterval: 1.4,
    range: 9,
    projectileType: 'pea',
    plantRole: 'shooter',
    color: '#4ade80',
    accentColor: '#16a34a'
  },
  plant_thornnut: {
    id: 'plant_thornnut',
    name: 'Thorn-Nut Barrier',
    description: 'Extremely durable wall that stalls advancing undead.',
    cost: 50,
    cooldown: 18.0,
    health: 1200,
    attackDamage: 0,
    attackInterval: 0,
    range: 0,
    projectileType: 'none',
    plantRole: 'wall',
    color: '#92400e',
    accentColor: '#78350f'
  },
  plant_frostwillow: {
    id: 'plant_frostwillow',
    name: 'Frost Willow',
    description: 'Fires chilling ice peas that slow zombie movement by 50%.',
    cost: 175,
    cooldown: 8.0,
    health: 300,
    attackDamage: 20,
    attackInterval: 1.4,
    range: 9,
    projectileType: 'frost',
    plantRole: 'slow',
    color: '#38bdf8',
    accentColor: '#0284c7'
  },
  plant_spikemoss: {
    id: 'plant_spikemoss',
    name: 'Spike Bramble',
    description: 'Ground trap that pierces and damages zombies walking over it.',
    cost: 100,
    cooldown: 8.0,
    health: 450,
    attackDamage: 25,
    attackInterval: 0.8,
    range: 1,
    projectileType: 'none',
    plantRole: 'trap',
    color: '#84cc16',
    accentColor: '#4d7c0f'
  },
  plant_cherrybomb: {
    id: 'plant_cherrybomb',
    name: 'Cherry Detonator',
    description: 'Detonates instantly in a 3x3 area, dealing massive 500 damage.',
    cost: 150,
    cooldown: 25.0,
    health: 100,
    attackDamage: 500,
    attackInterval: 1.0,
    range: 1,
    projectileType: 'none',
    plantRole: 'bomb',
    isInstantBomb: true,
    color: '#ef4444',
    accentColor: '#b91c1c'
  },
  plant_chomper: {
    id: 'plant_chomper',
    name: 'Chomper Fly-Trap',
    description: 'Devours normal-sized zombies whole, then digests slowly.',
    cost: 150,
    cooldown: 10.0,
    health: 350,
    attackDamage: 400,
    attackInterval: 12.0,
    range: 1,
    projectileType: 'none',
    plantRole: 'special',
    color: '#a855f7',
    accentColor: '#7e22ce'
  },
  plant_plasmaorchid: {
    id: 'plant_plasmaorchid',
    name: 'Plasma Orchid',
    description: 'Fires a continuous piercing laser beam across the entire lane.',
    cost: 200,
    cooldown: 12.0,
    health: 300,
    attackDamage: 38,
    attackInterval: 1.6,
    range: 9,
    projectileType: 'plasma',
    plantRole: 'shooter',
    color: '#ec4899',
    accentColor: '#be185d'
  },
  plant_aurablossom: {
    id: 'plant_aurablossom',
    name: 'Aura Blossom',
    description: 'Increases attack speed of adjacent plants by +35% and heals.',
    cost: 125,
    cooldown: 12.0,
    health: 300,
    attackDamage: 0,
    attackInterval: 3.0,
    range: 1,
    projectileType: 'none',
    plantRole: 'support',
    color: '#f472b6',
    accentColor: '#db2777'
  },
  plant_twincannon: {
    id: 'plant_twincannon',
    name: 'Twin-Cannon Rose',
    description: 'Fires 2 rapid high-velocity thorns simultaneously.',
    cost: 200,
    cooldown: 10.0,
    health: 300,
    attackDamage: 44,
    attackInterval: 1.4,
    range: 9,
    projectileType: 'thorn',
    plantRole: 'shooter',
    color: '#10b981',
    accentColor: '#047857'
  },
  plant_prismsun: {
    id: 'plant_prismsun',
    name: 'Prism Sunflower',
    description: 'Generates triple 75 Solar Energy bundles.',
    cost: 125,
    cooldown: 10.0,
    health: 300,
    attackDamage: 0,
    attackInterval: 9.0,
    range: 0,
    projectileType: 'none',
    plantRole: 'sun',
    color: '#fde047',
    accentColor: '#ca8a04'
  },
  plant_hypnoshroom: {
    id: 'plant_hypnoshroom',
    name: 'Hypno-Shroom',
    description: 'When eaten by a zombie, turns it friendly to fight for plants!',
    cost: 75,
    cooldown: 20.0,
    health: 100,
    attackDamage: 0,
    attackInterval: 0,
    range: 0,
    projectileType: 'none',
    plantRole: 'special',
    color: '#c084fc',
    accentColor: '#9333ea'
  },
  plant_melonpult: {
    id: 'plant_melonpult',
    name: 'Doom Melon-Pult',
    description: 'Lobs heavy explosive melons dealing area damage across rows.',
    cost: 300,
    cooldown: 15.0,
    health: 350,
    attackDamage: 75,
    attackInterval: 2.2,
    range: 9,
    projectileType: 'melon',
    plantRole: 'shooter',
    color: '#065f46',
    accentColor: '#047857'
  },
  plant_magnetlily: {
    id: 'plant_magnetlily',
    name: 'Magnet Lily',
    description: 'Disarms helmets and metallic armor from advancing zombies.',
    cost: 100,
    cooldown: 14.0,
    health: 300,
    attackDamage: 0,
    attackInterval: 8.0,
    range: 4,
    projectileType: 'none',
    plantRole: 'support',
    color: '#64748b',
    accentColor: '#475569'
  },
  plant_gatlingrose: {
    id: 'plant_gatlingrose',
    name: 'Gatling Rose',
    description: 'Unleashes a barrage of 4 rapid thorns at high speed.',
    cost: 275,
    cooldown: 18.0,
    health: 350,
    attackDamage: 88,
    attackInterval: 1.5,
    range: 9,
    projectileType: 'thorn',
    plantRole: 'shooter',
    color: '#059669',
    accentColor: '#064e3b'
  },
  plant_coccannon: {
    id: 'plant_coccannon',
    name: 'Colossus Cannon',
    description: 'Supreme siege artillery. Massive devastating missile blast.',
    cost: 400,
    cooldown: 30.0,
    health: 400,
    attackDamage: 600,
    attackInterval: 20.0,
    range: 9,
    projectileType: 'melon',
    plantRole: 'bomb',
    color: '#ea580c',
    accentColor: '#c2410c'
  }
};

export const ZOMBIE_REGISTRY: Record<string, ZombieCardDef> = {
  zomb_walker: {
    id: 'zomb_walker',
    name: 'Walker Ghoul',
    description: 'Basic disposable shock trooper.',
    cost: 50,
    cooldown: 4.0,
    health: 180,
    speed: 0.6,
    biteDamage: 25,
    biteInterval: 0.8,
    armor: 0,
    zombieRole: 'basic',
    color: '#6b7280',
    accentColor: '#4b5563'
  },
  zomb_buckethead: {
    id: 'zomb_buckethead',
    name: 'Buckethead Brute',
    description: 'Heavy armor bucket that absorbs heavy damage.',
    cost: 125,
    cooldown: 8.0,
    health: 650,
    speed: 0.55,
    biteDamage: 30,
    biteInterval: 0.8,
    armor: 15,
    zombieRole: 'tank',
    color: '#94a3b8',
    accentColor: '#64748b'
  },
  zomb_imprunner: {
    id: 'zomb_imprunner',
    name: 'Imp Runner',
    description: 'Ultra-fast little ghoul sprinting past defenses.',
    cost: 50,
    cooldown: 5.0,
    health: 90,
    speed: 1.4,
    biteDamage: 18,
    biteInterval: 0.5,
    armor: 0,
    zombieRole: 'runner',
    color: '#fb923c',
    accentColor: '#ea580c'
  },
  zomb_polevault: {
    id: 'zomb_polevault',
    name: 'Pole-Vault Stalker',
    description: 'Sprints fast and vaults over the first plant in the lane.',
    cost: 100,
    cooldown: 9.0,
    health: 260,
    speed: 1.1,
    biteDamage: 25,
    biteInterval: 0.8,
    armor: 0,
    canVault: true,
    zombieRole: 'vault',
    color: '#a855f7',
    accentColor: '#9333ea'
  },
  zomb_miner: {
    id: 'zomb_miner',
    name: 'Tombstone Miner',
    description: 'Burrows underground and emerges behind plant lines at col 3.',
    cost: 125,
    cooldown: 12.0,
    health: 300,
    speed: 0.8,
    biteDamage: 30,
    biteInterval: 0.8,
    armor: 0,
    canBurrow: true,
    zombieRole: 'burrow',
    color: '#b45309',
    accentColor: '#78350f'
  },
  zomb_necromancer: {
    id: 'zomb_necromancer',
    name: 'Necromancer Cultist',
    description: 'Summons auxiliary skeleton walkers every 7 seconds.',
    cost: 175,
    cooldown: 14.0,
    health: 350,
    speed: 0.45,
    biteDamage: 20,
    biteInterval: 1.0,
    armor: 0,
    zombieRole: 'ranged',
    color: '#8b5cf6',
    accentColor: '#6d28d9'
  },
  zomb_gargantuar: {
    id: 'zomb_gargantuar',
    name: 'Gargantuar Behemoth',
    description: 'Colossal titan crushing plants in one strike + throws an imp at 50% HP.',
    cost: 300,
    cooldown: 25.0,
    health: 1400,
    speed: 0.4,
    biteDamage: 120,
    biteInterval: 1.4,
    armor: 25,
    zombieRole: 'boss',
    color: '#1e293b',
    accentColor: '#0f172a'
  },
  zomb_plaguespitter: {
    id: 'zomb_plaguespitter',
    name: 'Plague Spitter',
    description: 'Spits corrosive acid at plants from 3 tiles away.',
    cost: 150,
    cooldown: 10.0,
    health: 280,
    speed: 0.5,
    biteDamage: 35,
    biteInterval: 1.2,
    armor: 0,
    zombieRole: 'ranged',
    color: '#10b981',
    accentColor: '#059669'
  },
  zomb_screendoor: {
    id: 'zomb_screendoor',
    name: 'Screen-Door Defender',
    description: 'Carries a metal mesh door shielding against straight shots.',
    cost: 100,
    cooldown: 8.0,
    health: 500,
    speed: 0.55,
    biteDamage: 25,
    biteInterval: 0.8,
    armor: 10,
    zombieRole: 'tank',
    color: '#334155',
    accentColor: '#1e293b'
  },
  zomb_balloon: {
    id: 'zomb_balloon',
    name: 'Balloon Aviator',
    description: 'Floats over ground plants straight toward the core.',
    cost: 100,
    cooldown: 10.0,
    health: 180,
    speed: 0.7,
    biteDamage: 20,
    biteInterval: 0.8,
    armor: 0,
    isFlying: true,
    zombieRole: 'flying',
    color: '#ef4444',
    accentColor: '#dc2626'
  },
  zomb_football: {
    id: 'zomb_football',
    name: 'Football Juggernaut',
    description: 'Heavy armored helmet + high speed charging down the lane.',
    cost: 200,
    cooldown: 14.0,
    health: 750,
    speed: 0.95,
    biteDamage: 40,
    biteInterval: 0.7,
    armor: 20,
    zombieRole: 'tank',
    color: '#991b1b',
    accentColor: '#7f1d1d'
  },
  zomb_discolich: {
    id: 'zomb_discolich',
    name: 'Disco Lich',
    description: 'Dances forward and summons 4 backup dancers in adjacent lanes.',
    cost: 225,
    cooldown: 16.0,
    health: 400,
    speed: 0.6,
    biteDamage: 30,
    biteInterval: 0.8,
    armor: 5,
    zombieRole: 'boss',
    color: '#ec4899',
    accentColor: '#db2777'
  },
  zomb_iceroller: {
    id: 'zomb_iceroller',
    name: 'Zamboni Ice-Roller',
    description: 'Crushes all plants on its path and leaves a frozen trail.',
    cost: 250,
    cooldown: 20.0,
    health: 600,
    speed: 0.65,
    biteDamage: 100,
    biteInterval: 1.0,
    armor: 15,
    zombieRole: 'boss',
    color: '#38bdf8',
    accentColor: '#0284c7'
  },
  zomb_catapult: {
    id: 'zomb_catapult',
    name: 'Catapult Mortar',
    description: 'Launches heavy rocks over defenses into backline plants.',
    cost: 200,
    cooldown: 16.0,
    health: 450,
    speed: 0.4,
    biteDamage: 60,
    biteInterval: 2.0,
    armor: 10,
    zombieRole: 'ranged',
    color: '#713f12',
    accentColor: '#854d0e'
  },
  zomb_bungee: {
    id: 'zomb_bungee',
    name: 'Bungee Marauder',
    description: 'Drops from the ceiling to abduct and remove a key plant.',
    cost: 125,
    cooldown: 15.0,
    health: 200,
    speed: 1.2,
    biteDamage: 50,
    biteInterval: 1.0,
    armor: 0,
    zombieRole: 'special',
    color: '#475569',
    accentColor: '#334155'
  },
  zomb_mechavatar: {
    id: 'zomb_mechavatar',
    name: 'Dr. Zomboss Mech',
    description: 'Supreme war machine with laser cannons and heavy armor.',
    cost: 450,
    cooldown: 35.0,
    health: 2200,
    speed: 0.35,
    biteDamage: 150,
    biteInterval: 1.5,
    armor: 30,
    zombieRole: 'boss',
    color: '#4c1d95',
    accentColor: '#3b0764'
  }
};

export const COMMANDER_SPELLS: Record<string, CommanderSpellDef> = {
  // Flora Spells
  spell_sun_surge: {
    id: 'spell_sun_surge',
    name: 'Solar Flare Surge',
    description: 'Instantly grants +150 Solar Energy.',
    faction: 'PLANTS',
    cost: 0,
    cooldown: 40.0,
    color: '#facc15'
  },
  spell_overcharge: {
    id: 'spell_overcharge',
    name: 'Fertilizer Overcharge',
    description: 'Boosts attack speed of all plants on a lane by +100% for 8s.',
    faction: 'PLANTS',
    cost: 75,
    cooldown: 30.0,
    color: '#22c55e'
  },
  spell_shield: {
    id: 'spell_shield',
    name: 'Aegis Barrier',
    description: 'Grants 8 seconds of absolute invulnerability to a chosen plant.',
    faction: 'PLANTS',
    cost: 50,
    cooldown: 25.0,
    color: '#06b6d4'
  },
  spell_blizzard: {
    id: 'spell_blizzard',
    name: 'Blizzard Flash',
    description: 'Freezes all zombies on the entire battlefield for 4.5 seconds.',
    faction: 'PLANTS',
    cost: 125,
    cooldown: 50.0,
    color: '#38bdf8'
  },

  // Undead Spells
  spell_unholy_rush: {
    id: 'spell_unholy_rush',
    name: 'Unholy Sprint',
    description: 'Boosts movement speed of all zombies by +50% for 6 seconds.',
    faction: 'ZOMBIES',
    cost: 50,
    cooldown: 30.0,
    color: '#a855f7'
  },
  spell_horde_surge: {
    id: 'spell_horde_surge',
    name: 'Horde Awakening',
    description: 'Spawns 5 Walker Ghouls simultaneously across all 5 lanes.',
    faction: 'ZOMBIES',
    cost: 150,
    cooldown: 45.0,
    color: '#ef4444'
  },
  spell_fog: {
    id: 'spell_fog',
    name: 'Noxious Fog',
    description: 'Blinds plants on a selected lane, reducing their range for 8s.',
    faction: 'ZOMBIES',
    cost: 75,
    cooldown: 35.0,
    color: '#10b981'
  },
  spell_rage: {
    id: 'spell_rage',
    name: 'Frenzied Bite',
    description: 'Doubles bite damage of all active zombies for 6 seconds.',
    faction: 'ZOMBIES',
    cost: 100,
    cooldown: 40.0,
    color: '#f97316'
  }
};

export const MAP_CONFIGS: Record<MapType, { name: string; description: string; bgColor: string; hazards: Record<string, TileHazard> }> = {
  verdant_grove: {
    name: 'Verdant Grove',
    description: 'Classic peaceful garden with high solar fertility.',
    bgColor: '#14532d',
    hazards: {
      '2_1': 'sun_well',
      '2_3': 'sun_well'
    }
  },
  necro_swamp: {
    name: 'Sunken Necro-Swamp',
    description: 'Toxic murky waters slow both advancing zombies and roots.',
    bgColor: '#064e3b',
    hazards: {
      '4_0': 'toxic_puddle',
      '4_2': 'toxic_puddle',
      '4_4': 'toxic_puddle'
    }
  },
  bio_lab: {
    name: 'Abandoned Bio-Lab',
    description: 'Mutagenic speed pads accelerate moving units.',
    bgColor: '#1e1b4b',
    hazards: {
      '5_1': 'boost_speed',
      '5_3': 'boost_speed',
      '3_2': 'obstacle'
    }
  },
  astral_wasteland: {
    name: 'Astral Wasteland',
    description: 'Celestial energy vortexes and crystalline obstructions.',
    bgColor: '#0f172a',
    hazards: {
      '3_0': 'obstacle',
      '3_4': 'obstacle',
      '1_2': 'sun_well'
    }
  }
};
